AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation for Catalogue Application UI 
Parameters:
  S3BucketForCatalogueUI:
    Type: String

Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref S3BucketForCatalogueUI
            VersioningConfiguration:
              Status: Enabled
            WebsiteConfiguration:
              IndexDocument: "index.html"

    S3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  Action:
                  - s3:GetObject
                  Effect: Allow
                  Resource: !Sub
                    - arn:aws:s3:::${bucketname}/*
                    - { bucketname: !Ref S3Bucket }
                  Principal: "*"
    
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3